format_version: 3
pipelines:
  experiment:
    group: defaultGroup
    display_order: -1
    label_template: "${COUNT}"
    lock_behavior: none
    materials:
      experiment:
        git: git@github.com:afridshaikhtw/test.git
        branch: main
        auto_update: true
        destination: experiment
        name: experiment
    stages:
      - build_experiment:
          fetch_materials: true
          jobs:
            say_hello:
              timeout: 0
              tasks:
                - exec:
                    arguments:
                      - "Experimental pipeline test"
                    command: echo
