format_version: 3
pipelines:
  experiment:
    group: defaultGroup
    display_order: -1
    label_template: "${COUNT}"
    lock_behavior: none
    materials:
      experiment:
        git: https://github.com/afridshaikhtw/test.git
        branch: main
        auto_update: true
        destination: experiment
        name: experiment
    stages:
      - create_file:
          fetch_materials: true
          jobs:
            create_file:
              timeout: 0
              tasks:
                - exec:
                    arguments:
                      - file.txt
                    command: touch
      - write_file:
          # fetch_materials: true
          jobs:
            write_file:
              timeout: 0
              tasks:
                - exec:
                    arguments:
                      - "-ltra"
                    command: ls
                - exec:
                    arguments:
                      - "\"abbxyz\" > file.txt"
                    command: echo 
