format_version: 3
pipelines:
  experiment: # definition of mypipe1 pipeline
    group: experiment # note that the group name can contain only of alphanumeric & underscore characters
    display_order: -1
    label_template: "${COUNT}"
    lock_behavior: none
    parameters: # list of parameters that can be configured for a pipeline
      param1: value1
    materials:
      experiment: # this is the name of material, the name can contain only of alphanumeric & underscore characters
        # keyword git says about type of material and url at once
        git: git@github.com:afridshaikhtw/test.git
        branch: main
        username: afridshaikhtw
    stages: # list of stages in order
    - build: # name of stage
        fetch_materials: true
        jobs:
        - exec:
            arguments:
            - "Experimental pipeline"
            command: echo
